### ISSUE TITLE
iOS license link broken

### ISSUE THREAD

**Issue by lhammond** [RadiusNetworks/proximitykit-documentation#5]
hey guys, this 404'd for me at 10/30/2014 5:30 PM EST
https://proximitykit.radiusnetworks.com/docs/license

![image](https://cloud.githubusercontent.com/assets/229602/4852449/228af7e8-607c-11e4-90c9-191f15c657b9.png)

**Comment by syoder** [comment]
I believe this is fixed now.  The above mentioned URL has an escaped `/` in it, which it shouldn't (and the thing that generated this link has been fixed, I believe).  That is causing the links to base their relative paths on `/docs/ios%2Fgetting-started` instead of `/docs/ios`
